### PR TITLE
About and FAQ sections

### PR DESCRIPTION
**Pull request by isovector**

### CODE REVIEW

**Comment by godwin-morwin** [comment]
Hi , Are you adding the about and faQ  ?

**Comment by isovector** [comment]
@Godwindaniel10 yup. I'm adding the about and FAQ sections!

**Comment by godwin-morwin** [comment]
ok good , seeing if i can contribute to your project

**Comment by isovector** [comment]
@Godwindaniel10 right now, the biggest help would be to use wingman and report bugs if it doesn't work, or doesn't give you the result you had in mind!

**Pull request merged**
